language: python
python:
    - 3.4
    - 3.3
    - 2.7
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
sudo: false
addons:
  apt:
    packages:
    - texlive-base
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - wget https://7de4dfdec62155b49b44-d726a73613a1989d29b147f20996e7c1.ssl.cf2.rackcdn.com/pandoc-1.12.3-linux-debian-x86_64.zip && unzip pandoc-1.12.3-linux-debian-x86_64.zip
    - pip install -f travis-wheels/wheelhouse . coveralls -r requirements.txt
    - pip install nbconvert[execute,serve,test]
    - python -m ipykernel.kernelspec --user
script:
    - nosetests -w /tmp --with-coverage --cover-package nbconvert nbconvert
after_success:
    - coveralls
