name: nbconvert_docs
channels:
  - conda-forge
dependencies:
- python>=3.5
- pandoc
- nbformat
- jupyter_client
- ipython
- sphinx>=1.3.6
- sphinx_rtd_theme
- tornado
- entrypoints
- pip:
    - nbsphinx
