name: nbconvert_docs
channels:
  - conda-forge
dependencies:
- python==3.5
- pandoc
- nbformat
- jupyter_client
- ipython
- sphinx>=1.5.1
- sphinx_rtd_theme
- tornado
- entrypoints
- pip:
    - nbsphinx>=0.2.12
    - sphinxcontrib_github_alt
